# Generated by Django 5.2.7 on 2025-11-20 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('can_access_premium', 'Can access premium features'), ('can_manage_content', 'Can manage all content'), ('can_manage_users', 'Can manage users')]},
        ),
    ]
