# Generated by Django 5.2.7 on 2025-11-20 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0002_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('can_create_book', 'Can create book'), ('can_view', 'Can view books'), ('can_edit_book', 'Can edit book'), ('can_delete_book', 'Can delete book'), ('can_view_premium_books', 'Can view premium books'), ('can_publish_book', 'Can publish new books'), ('can_delete_any_book', 'Can delete any book')]},
        ),
    ]
