# Generated by Django 5.2.7 on 2025-11-18 21:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('can_access_premium', 'Can access premium features'), ('can_manage_content', 'Can manage all content')]},
        ),
        migrations.AddField(
            model_name='book',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='book',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='membership_type',
            field=models.CharField(choices=[('basic', 'Basic'), ('premium', 'Premium'), ('admin', 'Admin')], default='basic', max_length=20),
        ),
    ]
